# Generated by Django 6.0.3 on 2026-03-25 02:13

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[
                    django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('description', models.TextField(blank=True, verbose_name='店铺描述')),
                ('address', models.TextField(verbose_name='店铺地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('shop_type', models.CharField(
                    choices=[('restaurant', '餐厅'), ('cafe', '咖啡厅'), ('bar', '酒吧'), ('bakery', '烘焙店'),
                             ('other', '其他')], default='restaurant', max_length=20)),
                ('opening_hours', models.JSONField(default=dict, verbose_name='营业时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否营业')),
                ('allow_delivery', models.BooleanField(default=True, verbose_name='允许外卖')),
                ('allow_pickup', models.BooleanField(default=True, verbose_name='允许自取')),
                ('allow_dine_in', models.BooleanField(default=True, verbose_name='允许堂食')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='配送费')),
                ('minimum_order_amount',
                 models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='最低起送价')),
                ('delivery_radius', models.IntegerField(default=5, verbose_name='配送半径(公里)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/logo/', verbose_name='店铺Logo')),
                ('banner',
                 models.ImageField(blank=True, null=True, upload_to='shops/banner/', verbose_name='店铺横幅')),
                ('payment_methods', models.JSONField(default=dict, verbose_name='支付方式')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
                'db_table': 'shops',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20, verbose_name='桌台号')),
                ('table_name', models.CharField(blank=True, max_length=50, verbose_name='桌台名称')),
                ('table_type', models.CharField(
                    choices=[('standard', '标准桌'), ('booth', '卡座'), ('bar', '吧台'), ('private', '包间'),
                             ('outdoor', '户外桌')], default='standard', max_length=20, verbose_name='桌台类型')),
                ('min_capacity', models.IntegerField(default=2, verbose_name='最小人数')),
                ('max_capacity', models.IntegerField(default=4, verbose_name='最大人数')),
                ('status', models.CharField(
                    choices=[('available', '空闲'), ('occupied', '占用'), ('reserved', '预订'), ('cleaning', '清洁中'),
                             ('maintenance', '维护中')], default='available', max_length=20, verbose_name='状态')),
                ('qr_code',
                 models.ImageField(blank=True, null=True, upload_to='tables/qr_codes/', verbose_name='二维码')),
                ('floor', models.CharField(blank=True, max_length=50, verbose_name='楼层')),
                ('section', models.CharField(blank=True, max_length=50, verbose_name='区域')),
                ('position_x', models.IntegerField(default=0, verbose_name='X坐标')),
                ('position_y', models.IntegerField(default=0, verbose_name='Y坐标')),
                ('features', models.JSONField(default=dict, verbose_name='特色功能')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '桌台',
                'verbose_name_plural': '桌台',
                'db_table': 'tables',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains',
                                             to='shops.shop')),
            ],
            options={
                'verbose_name': '店铺域名',
                'verbose_name_plural': '店铺域名',
                'db_table': 'shop_domains',
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_confirm_order', models.BooleanField(default=False, verbose_name='自动确认订单')),
                ('order_timeout', models.IntegerField(default=15, verbose_name='订单超时时间(分钟)')),
                ('auto_print_order', models.BooleanField(default=False, verbose_name='自动打印订单')),
                ('printer_config', models.JSONField(default=dict, verbose_name='打印机配置')),
                ('email_notification', models.BooleanField(default=False, verbose_name='邮件通知')),
                ('sms_notification', models.BooleanField(default=False, verbose_name='短信通知')),
                ('points_enabled', models.BooleanField(default=True, verbose_name='启用积分系统')),
                ('points_ratio',
                 models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='积分比例')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings',
                                              to='shops.shop')),
            ],
            options={
                'verbose_name': '店铺设置',
                'verbose_name_plural': '店铺设置',
                'db_table': 'shop_settings',
            },
        ),
        migrations.CreateModel(
            name='ShopStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(
                    choices=[('owner', '店主'), ('manager', '店长'), ('staff', '员工'), ('cashier', '收银员')],
                    default='staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('permissions', models.JSONField(default=dict, verbose_name='权限配置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='shops.shop')),
            ],
            options={
                'verbose_name': '店铺员工',
                'verbose_name_plural': '店铺员工',
                'db_table': 'shop_staff',
            },
        ),
    ]
