# Generated by Django 6.0.3 on 2026-03-25 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_staff',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='table',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables',
                                    to='shops.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='shopstaff',
            unique_together={('user', 'shop')},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('shop', 'table_number')},
        ),
    ]
