# Generated by Django 6.0.6 on 2026-07-22 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shopapply",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="审核人",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="shop",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="shopstaff",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="shopstaff",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shop_staff",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tables",
                to="shops.shop",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shopstaff",
            unique_together={("user", "shop")},
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("shop", "table_number")},
        ),
    ]
