# Generated by Django 6.0.6 on 2026-07-21 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopApply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=100, verbose_name="联系人"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="联系电话"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="联系邮箱"),
                ),
                (
                    "shop_name",
                    models.CharField(max_length=200, verbose_name="店铺名称"),
                ),
                (
                    "shop_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "餐厅"),
                            ("cafe", "咖啡厅"),
                            ("bar", "酒吧"),
                            ("bakery", "烘焙店"),
                            ("other", "其他"),
                        ],
                        default="restaurant",
                        max_length=20,
                        verbose_name="店铺类型",
                    ),
                ),
                ("shop_address", models.TextField(blank=True, verbose_name="店铺地址")),
                (
                    "shop_description",
                    models.TextField(blank=True, verbose_name="店铺描述"),
                ),
                (
                    "account_password",
                    models.CharField(max_length=128, verbose_name="登录密码"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "review_remark",
                    models.TextField(blank=True, verbose_name="审核备注"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "入驻申请",
                "verbose_name_plural": "入驻申请",
                "db_table": "shop_applies",
                "ordering": ["-created_at"],
            },
        ),
    ]
