# Generated by manual — adds account_password, setup_token, setup_completed fields to ShopApply
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopapply',
            name='account_password',
            field=models.CharField(blank=True, max_length=256, verbose_name='登录密码'),
        ),
        migrations.AddField(
            model_name='shopapply',
            name='setup_token',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='设置令牌'),
        ),
        migrations.AddField(
            model_name='shopapply',
            name='setup_completed',
            field=models.BooleanField(default=False, verbose_name='是否完成设置'),
        ),
        migrations.AddField(
            model_name='shopapply',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='设置完成时间'),
        ),
    ]
