# Generated by Django 6.0.3 on 2026-07-21 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopapply",
            name="account_password",
        ),
    ]
