# Generated by Django 6.0.6 on 2026-07-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0003_remove_shopapply_account_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="纬度",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="经度",
            ),
        ),
    ]
