# Generated by manual — adds shop FK to ShopApply (separate from 0003 because 0003 was already applied)
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0003_shopapply_account_password_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopapply',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='shop_applies', to='shops.shop', verbose_name='关联店铺'),
        ),
    ]
