# Generated by Django 6.0.6 on 2026-07-22 01:56

from decimal import Decimal

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptchaConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("none", "不启用"),
                            ("geetest", "极验 GEETEST"),
                            ("tencent", "腾讯云验证码"),
                            ("aliyun", "阿里云验证码"),
                            ("dingxiang", "顶象验证码"),
                            ("netease", "网易易盾验证码"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="验证平台",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="启用人机验证"),
                ),
                (
                    "geetest_captcha_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="极验 captcha_id",
                    ),
                ),
                (
                    "geetest_captcha_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="极验 captcha_key"
                    ),
                ),
                (
                    "tencent_app_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="腾讯云 Captcha AppId",
                    ),
                ),
                (
                    "tencent_secret_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="腾讯云 Captcha SecretKey"
                    ),
                ),
                (
                    "aliyun_app_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="阿里云验证码 AppKey",
                    ),
                ),
                (
                    "aliyun_secret_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="阿里云验证码 SecretKey"
                    ),
                ),
                (
                    "dingxiang_app_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="顶象 appId",
                    ),
                ),
                (
                    "dingxiang_app_secret",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="顶象 appSecret"
                    ),
                ),
                (
                    "netease_captcha_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="易盾 captchaId",
                    ),
                ),
                (
                    "netease_secret_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="易盾 secretKey"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "人机验证配置",
                "verbose_name_plural": "人机验证配置",
                "db_table": "captcha_config",
            },
        ),
        migrations.CreateModel(
            name="SocialLoginConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weixin_app_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="微信 AppID",
                    ),
                ),
                (
                    "weixin_app_secret",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="微信 AppSecret"
                    ),
                ),
                (
                    "weixin_scope",
                    models.CharField(
                        default="snsapi_login", max_length=50, verbose_name="微信 Scope"
                    ),
                ),
                (
                    "alipay_app_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="支付宝 AppID",
                    ),
                ),
                (
                    "alipay_private_key",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default="", verbose_name="支付宝应用私钥"
                    ),
                ),
                (
                    "alipay_public_key",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default="", verbose_name="支付宝公钥"
                    ),
                ),
                (
                    "alipay_scope",
                    models.CharField(
                        default="auth_user", max_length=50, verbose_name="支付宝 Scope"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用第三方登录"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "第三方登录配置",
                "verbose_name_plural": "第三方登录配置",
                "db_table": "social_login_config",
            },
        ),
        migrations.CreateModel(
            name="VerifyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_phone_login",
                    models.BooleanField(
                        default=True, verbose_name="启用手机验证码登录"
                    ),
                ),
                (
                    "enable_email_login",
                    models.BooleanField(
                        default=False, verbose_name="启用邮箱验证码登录"
                    ),
                ),
                (
                    "login_mode",
                    models.CharField(
                        choices=[
                            ("any", "手机或邮箱均可"),
                            ("phone_only", "仅手机验证码"),
                            ("email_only", "仅邮箱验证码"),
                        ],
                        default="any",
                        max_length=20,
                        verbose_name="登录模式",
                    ),
                ),
                (
                    "code_length",
                    models.PositiveIntegerField(default=6, verbose_name="验证码位数"),
                ),
                (
                    "code_expire_seconds",
                    models.PositiveIntegerField(
                        default=300, verbose_name="验证码过期秒数"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="启用验证码登录功能"
                    ),
                ),
                (
                    "sms_provider",
                    models.CharField(
                        choices=[
                            ("console", "控制台输出（开发）"),
                            ("aliyun", "阿里云短信"),
                            ("tencent", "腾讯云短信"),
                        ],
                        default="console",
                        max_length=20,
                        verbose_name="短信服务商",
                    ),
                ),
                (
                    "aliyun_access_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="阿里云 AccessKey"
                    ),
                ),
                (
                    "aliyun_secret_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="阿里云 SecretKey"
                    ),
                ),
                (
                    "aliyun_sign_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="阿里云短信签名",
                    ),
                ),
                (
                    "aliyun_template_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="阿里云短信模板码",
                    ),
                ),
                (
                    "tencent_secret_id",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="腾讯云 SecretId"
                    ),
                ),
                (
                    "tencent_secret_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="腾讯云 SecretKey"
                    ),
                ),
                (
                    "tencent_sdk_app_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="腾讯云 SDK AppID",
                    ),
                ),
                (
                    "tencent_sign_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="腾讯云短信签名",
                    ),
                ),
                (
                    "tencent_template_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="腾讯云短信模板码",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="SMTP 服务器",
                    ),
                ),
                (
                    "email_port",
                    models.PositiveIntegerField(default=465, verbose_name="SMTP 端口"),
                ),
                (
                    "email_host_user",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="SMTP 用户名",
                    ),
                ),
                (
                    "email_host_password",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="SMTP 密码"
                    ),
                ),
                (
                    "email_use_tls",
                    models.BooleanField(default=False, verbose_name="使用 TLS"),
                ),
                (
                    "email_use_ssl",
                    models.BooleanField(default=True, verbose_name="使用 SSL"),
                ),
                (
                    "email_from",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="发件人地址",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "验证码与发信配置",
                "verbose_name_plural": "验证码与发信配置",
                "db_table": "verify_config",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("super_admin", "超级管理员"),
                            ("shop_owner", "店铺所有者"),
                            ("shop_staff", "店铺员工"),
                            ("customer", "顾客"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="生日"),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("points", models.IntegerField(default=0)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="账户余额",
                    ),
                ),
                (
                    "membership_level",
                    models.CharField(
                        choices=[
                            ("regular", "普通会员"),
                            ("silver", "银卡会员"),
                            ("gold", "金卡会员"),
                            ("platinum", "白金会员"),
                            ("diamond", "钻石会员"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="会员等级",
                    ),
                ),
                (
                    "membership_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="会员卡号",
                    ),
                ),
                (
                    "membership_expiry",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="会员到期时间"
                    ),
                ),
                (
                    "total_points",
                    models.IntegerField(default=0, verbose_name="累计积分"),
                ),
                (
                    "available_points",
                    models.IntegerField(default=0, verbose_name="可用积分"),
                ),
                (
                    "used_points",
                    models.IntegerField(default=0, verbose_name="已用积分"),
                ),
                (
                    "total_consumption",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="总消费金额",
                    ),
                ),
                (
                    "consumption_count",
                    models.IntegerField(default=0, verbose_name="消费次数"),
                ),
                (
                    "referral_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="推荐码",
                    ),
                ),
                (
                    "wechat_openid",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="微信OpenID"
                    ),
                ),
                (
                    "wechat_unionid",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="微信UnionID",
                    ),
                ),
                (
                    "alipay_user_id",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="支付宝用户ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="推荐人",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="MemberRecharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recharge_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="充值金额"
                    ),
                ),
                (
                    "gift_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="赠送金额",
                    ),
                ),
                (
                    "gift_points",
                    models.IntegerField(default=0, verbose_name="赠送积分"),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=50, verbose_name="支付方式"),
                ),
                (
                    "payment_status",
                    models.BooleanField(default=False, verbose_name="支付状态"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_recharges",
                        to="shops.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recharges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "会员充值",
                "verbose_name_plural": "会员充值",
                "db_table": "member_recharges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PointsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_type",
                    models.CharField(
                        choices=[
                            ("earn_order", "消费获得"),
                            ("earn_signin", "签到获得"),
                            ("earn_share", "分享获得"),
                            ("earn_referral", "推荐获得"),
                            ("consume_order", "消费抵扣"),
                            ("consume_gift", "兑换礼品"),
                            ("expire", "积分过期"),
                            ("adjust", "人工调整"),
                        ],
                        max_length=20,
                        verbose_name="积分类型",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="积分变化")),
                ("current_points", models.IntegerField(verbose_name="当前积分")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "reference_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="关联单据ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_logs",
                        to="shops.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="points_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "积分记录",
                "verbose_name_plural": "积分记录",
                "db_table": "points_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="收货人姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                ("province", models.CharField(max_length=50, verbose_name="省份")),
                ("city", models.CharField(max_length=50, verbose_name="城市")),
                ("district", models.CharField(max_length=50, verbose_name="区县")),
                ("detail", models.TextField(verbose_name="详细地址")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认"),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="地址标签"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户地址",
                "verbose_name_plural": "用户地址",
                "db_table": "user_addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerifyCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="手机号"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="邮箱"
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="验证码")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("register", "注册"),
                            ("bind", "绑定手机/邮箱"),
                        ],
                        default="login",
                        max_length=20,
                        verbose_name="用途",
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="已使用")),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "验证码",
                "verbose_name_plural": "验证码",
                "db_table": "verify_codes",
                "indexes": [
                    models.Index(
                        fields=["phone", "code", "purpose"],
                        name="verify_code_phone_248b16_idx",
                    ),
                    models.Index(
                        fields=["email", "code", "purpose"],
                        name="verify_code_email_a3dc64_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MembershipLevelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("regular", "普通会员"),
                            ("silver", "银卡会员"),
                            ("gold", "金卡会员"),
                            ("platinum", "白金会员"),
                            ("diamond", "钻石会员"),
                        ],
                        max_length=20,
                        verbose_name="等级",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="等级名称")),
                (
                    "min_points",
                    models.IntegerField(default=0, verbose_name="升级所需积分"),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                        verbose_name="折扣率",
                    ),
                ),
                (
                    "points_earn_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.1,
                        max_digits=5,
                        verbose_name="积分获取比例",
                    ),
                ),
                ("benefits", models.JSONField(default=dict, verbose_name="会员权益")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_levels",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "会员等级配置",
                "verbose_name_plural": "会员等级配置",
                "db_table": "membership_level_configs",
                "unique_together": {("shop", "level")},
            },
        ),
        migrations.CreateModel(
            name="PointsRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("order_earn", "消费获得积分"),
                            ("signin_earn", "签到获得积分"),
                            ("share_earn", "分享获得积分"),
                            ("referral_earn", "推荐获得积分"),
                            ("points_expire", "积分过期规则"),
                        ],
                        max_length=20,
                        verbose_name="规则类型",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                ("description", models.TextField(blank=True, verbose_name="规则描述")),
                ("config", models.JSONField(default=dict, verbose_name="规则配置")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_rules",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "积分规则",
                "verbose_name_plural": "积分规则",
                "db_table": "points_rules",
                "unique_together": {("shop", "rule_type")},
            },
        ),
        migrations.CreateModel(
            name="SocialAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("weixin", "微信"), ("alipay", "支付宝")],
                        max_length=20,
                        verbose_name="提供商",
                    ),
                ),
                (
                    "openid",
                    models.CharField(max_length=128, verbose_name="OpenID/用户ID"),
                ),
                (
                    "unionid",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="UnionID"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="额外数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="绑定时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="social_auths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "第三方账号绑定",
                "verbose_name_plural": "第三方账号绑定",
                "db_table": "social_auth",
                "indexes": [
                    models.Index(
                        fields=["provider", "openid"],
                        name="social_auth_provide_9b6a06_idx",
                    ),
                    models.Index(
                        fields=["user", "provider"],
                        name="social_auth_user_id_b19816_idx",
                    ),
                ],
                "unique_together": {("provider", "openid")},
            },
        ),
    ]
