# Generated by Django 6.0.6 on 2026-07-22 03:33

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("local", "本地存储（开发）"),
                            ("aliyun_oss", "阿里云 OSS"),
                            ("tencent_cos", "腾讯云 COS"),
                            ("qiniu", "七牛云 Kodo"),
                        ],
                        default="local",
                        max_length=20,
                        verbose_name="存储服务商",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用云存储"),
                ),
                (
                    "bucket",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Bucket/空间名称",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="地域/区域"
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="访问域名/CDN",
                    ),
                ),
                (
                    "path_prefix",
                    models.CharField(
                        blank=True,
                        default="uploads/",
                        max_length=100,
                        verbose_name="文件路径前缀",
                    ),
                ),
                (
                    "aliyun_access_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="阿里云 AccessKey"
                    ),
                ),
                (
                    "aliyun_secret_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="阿里云 SecretKey"
                    ),
                ),
                (
                    "tencent_secret_id",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="腾讯云 SecretId"
                    ),
                ),
                (
                    "tencent_secret_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="腾讯云 SecretKey"
                    ),
                ),
                (
                    "qiniu_access_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="七牛 AccessKey"
                    ),
                ),
                (
                    "qiniu_secret_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="七牛 SecretKey"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "云存储配置",
                "verbose_name_plural": "云存储配置",
                "db_table": "storage_config",
            },
        ),
    ]
