# Generated by Django 6.0.3 on 2026-07-21 16:21

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captchaconfig",
            name="aliyun_secret_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, default="", verbose_name="阿里云验证码 SecretKey"
            ),
        ),
        migrations.AlterField(
            model_name="captchaconfig",
            name="dingxiang_app_secret",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, default="", verbose_name="顶象 appSecret"
            ),
        ),
        migrations.AlterField(
            model_name="captchaconfig",
            name="geetest_captcha_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, default="", verbose_name="极验 captcha_key"
            ),
        ),
        migrations.AlterField(
            model_name="captchaconfig",
            name="netease_secret_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, default="", verbose_name="易盾 secretKey"
            ),
        ),
        migrations.AlterField(
            model_name="captchaconfig",
            name="tencent_secret_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, default="", verbose_name="腾讯云 Captcha SecretKey"
            ),
        ),
        migrations.AlterField(
            model_name="socialloginconfig",
            name="alipay_private_key",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default="", verbose_name="支付宝应用私钥"
            ),
        ),
        migrations.AlterField(
            model_name="socialloginconfig",
            name="alipay_public_key",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default="", verbose_name="支付宝公钥"
            ),
        ),
        migrations.AlterField(
            model_name="socialloginconfig",
            name="weixin_app_secret",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, default="", verbose_name="微信 AppSecret"
            ),
        ),
        migrations.AlterField(
            model_name="verifyconfig",
            name="aliyun_access_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, default="", verbose_name="阿里云 AccessKey"
            ),
        ),
        migrations.AlterField(
            model_name="verifyconfig",
            name="aliyun_secret_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, default="", verbose_name="阿里云 SecretKey"
            ),
        ),
        migrations.AlterField(
            model_name="verifyconfig",
            name="email_host_password",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, default="", verbose_name="SMTP 密码"
            ),
        ),
        migrations.AlterField(
            model_name="verifyconfig",
            name="tencent_secret_id",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, default="", verbose_name="腾讯云 SecretId"
            ),
        ),
        migrations.AlterField(
            model_name="verifyconfig",
            name="tencent_secret_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, default="", verbose_name="腾讯云 SecretKey"
            ),
        ),
    ]
