# Generated by Django 6.0.3 on 2026-04-07 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alipay_user_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='支付宝用户ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='微信OpenID'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_unionid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='微信UnionID'),
        ),
        migrations.CreateModel(
            name='SocialAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('weixin', '微信'), ('alipay', '支付宝')], max_length=20,
                                              verbose_name='提供商')),
                ('openid', models.CharField(max_length=128, verbose_name='OpenID/用户ID')),
                ('unionid', models.CharField(blank=True, max_length=128, null=True, verbose_name='UnionID')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_auths',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '第三方账号绑定',
                'verbose_name_plural': '第三方账号绑定',
                'db_table': 'social_auth',
                'indexes': [models.Index(fields=['provider', 'openid'], name='social_auth_provide_9b6a06_idx'),
                            models.Index(fields=['user', 'provider'], name='social_auth_user_id_b19816_idx')],
                'unique_together': {('provider', 'openid')},
            },
        ),
    ]
