# Generated by Django 6.0.6 on 2026-07-22 03:34

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_storageconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="DnsProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("manual", "手动配置（不自动解析）"),
                            ("dnspod", "腾讯云 DNSPod"),
                            ("aliyun_dns", "阿里云 DNS"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="DNS 服务商",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="启用自动域名解析"),
                ),
                (
                    "domain_suffix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="例如 yourdomain.com，分配的域名将为 shop-{id}.yourdomain.com",
                        max_length=200,
                        verbose_name="根域名",
                    ),
                ),
                (
                    "dnspod_secret_id",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="DNSPod SecretId"
                    ),
                ),
                (
                    "dnspod_secret_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="DNSPod SecretKey"
                    ),
                ),
                (
                    "aliyun_access_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="阿里云 AccessKey"
                    ),
                ),
                (
                    "aliyun_secret_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default="", verbose_name="阿里云 SecretKey"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "域名解析配置（DNSPod/阿里云DNS）",
                "verbose_name_plural": "域名解析配置（DNSPod/阿里云DNS）",
                "db_table": "dns_provider_config",
            },
        ),
    ]
