# Generated by Django 6.0.6 on 2026-07-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_alipay_user_id_user_wechat_openid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="账户余额"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="生日"),
        ),
    ]
