# Generated by Django 6.0.6 on 2026-07-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_balance_user_birthday"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLoginConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weixin_app_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="微信 AppID",
                    ),
                ),
                (
                    "weixin_app_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="微信 AppSecret",
                    ),
                ),
                (
                    "weixin_scope",
                    models.CharField(
                        default="snsapi_login", max_length=50, verbose_name="微信 Scope"
                    ),
                ),
                (
                    "alipay_app_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="支付宝 AppID",
                    ),
                ),
                (
                    "alipay_private_key",
                    models.TextField(
                        blank=True, default="", verbose_name="支付宝应用私钥"
                    ),
                ),
                (
                    "alipay_public_key",
                    models.TextField(blank=True, default="", verbose_name="支付宝公钥"),
                ),
                (
                    "alipay_scope",
                    models.CharField(
                        default="auth_user", max_length=50, verbose_name="支付宝 Scope"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用第三方登录"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "第三方登录配置",
                "verbose_name_plural": "第三方登录配置",
                "db_table": "social_login_config",
            },
        ),
    ]
