# Generated by Django 6.0.6 on 2026-07-21 14:45

from django.db import migrations


def create_default_config(apps, schema_editor):
    SocialLoginConfig = apps.get_model('users', 'SocialLoginConfig')
    if not SocialLoginConfig.objects.exists():
        SocialLoginConfig.objects.create(
            weixin_scope='snsapi_login',
            alipay_scope='auth_user',
            is_active=True,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_socialloginconfig"),
    ]

    operations = [
        migrations.RunPython(create_default_config, migrations.RunPython.noop),
    ]
