# Generated by Django 6.0.6 on 2026-07-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_seed_social_login_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_phone_login",
                    models.BooleanField(
                        default=True, verbose_name="启用手机验证码登录"
                    ),
                ),
                (
                    "enable_email_login",
                    models.BooleanField(
                        default=False, verbose_name="启用邮箱验证码登录"
                    ),
                ),
                (
                    "login_mode",
                    models.CharField(
                        choices=[
                            ("any", "手机或邮箱均可"),
                            ("phone_only", "仅手机验证码"),
                            ("email_only", "仅邮箱验证码"),
                        ],
                        default="any",
                        max_length=20,
                        verbose_name="登录模式",
                    ),
                ),
                (
                    "code_length",
                    models.PositiveIntegerField(default=6, verbose_name="验证码位数"),
                ),
                (
                    "code_expire_seconds",
                    models.PositiveIntegerField(
                        default=300, verbose_name="验证码过期秒数"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="启用验证码登录功能"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "验证码登录配置",
                "verbose_name_plural": "验证码登录配置",
                "db_table": "verify_config",
            },
        ),
        migrations.CreateModel(
            name="VerifyCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=15, verbose_name="手机号"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="邮箱"
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="验证码")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("register", "注册"),
                            ("bind", "绑定手机/邮箱"),
                        ],
                        default="login",
                        max_length=20,
                        verbose_name="用途",
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="已使用")),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "验证码",
                "verbose_name_plural": "验证码",
                "db_table": "verify_codes",
                "indexes": [
                    models.Index(
                        fields=["phone", "code", "purpose"],
                        name="verify_code_phone_248b16_idx",
                    ),
                    models.Index(
                        fields=["email", "code", "purpose"],
                        name="verify_code_email_a3dc64_idx",
                    ),
                ],
            },
        ),
    ]
