# Generated by Django 6.0.6 on 2026-07-21 14:51

from django.db import migrations


def create_default_verify_config(apps, schema_editor):
    VerifyConfig = apps.get_model('users', 'VerifyConfig')
    if not VerifyConfig.objects.exists():
        VerifyConfig.objects.create(
            enable_phone_login=True,
            enable_email_login=False,
            login_mode='any',
            code_length=6,
            code_expire_seconds=300,
            is_active=True,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_verifyconfig_verifycode"),
    ]

    operations = [
        migrations.RunPython(create_default_verify_config, migrations.RunPython.noop),
    ]
