# Generated by Django 6.0.6 on 2026-07-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_seed_verify_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptchaConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("none", "不启用"),
                            ("geetest", "极验 GEETEST"),
                            ("tencent", "腾讯云验证码"),
                            ("aliyun", "阿里云验证码"),
                            ("dingxiang", "顶象验证码"),
                            ("netease", "网易易盾验证码"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="验证平台",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="启用人机验证"),
                ),
                (
                    "geetest_captcha_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="极验 captcha_id",
                    ),
                ),
                (
                    "geetest_captcha_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="极验 captcha_key",
                    ),
                ),
                (
                    "tencent_app_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="腾讯云 Captcha AppId",
                    ),
                ),
                (
                    "tencent_secret_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="腾讯云 Captcha SecretKey",
                    ),
                ),
                (
                    "aliyun_app_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="阿里云验证码 AppKey",
                    ),
                ),
                (
                    "aliyun_secret_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="阿里云验证码 SecretKey",
                    ),
                ),
                (
                    "dingxiang_app_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="顶象 appId",
                    ),
                ),
                (
                    "dingxiang_app_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="顶象 appSecret",
                    ),
                ),
                (
                    "netease_captcha_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="易盾 captchaId",
                    ),
                ),
                (
                    "netease_secret_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="易盾 secretKey",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "人机验证配置",
                "verbose_name_plural": "人机验证配置",
                "db_table": "captcha_config",
            },
        ),
        migrations.AlterModelOptions(
            name="verifyconfig",
            options={
                "verbose_name": "验证码与发信配置",
                "verbose_name_plural": "验证码与发信配置",
            },
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="aliyun_access_key",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="阿里云 AccessKey"
            ),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="aliyun_secret_key",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="阿里云 SecretKey"
            ),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="aliyun_sign_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="阿里云短信签名"
            ),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="aliyun_template_code",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="阿里云短信模板码"
            ),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="email_from",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="发件人地址"
            ),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="email_host",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="SMTP 服务器"
            ),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="email_host_password",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="SMTP 密码"
            ),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="email_host_user",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="SMTP 用户名"
            ),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="email_port",
            field=models.PositiveIntegerField(default=465, verbose_name="SMTP 端口"),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="email_use_ssl",
            field=models.BooleanField(default=True, verbose_name="使用 SSL"),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="email_use_tls",
            field=models.BooleanField(default=False, verbose_name="使用 TLS"),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="sms_provider",
            field=models.CharField(
                choices=[
                    ("console", "控制台输出（开发）"),
                    ("aliyun", "阿里云短信"),
                    ("tencent", "腾讯云短信"),
                ],
                default="console",
                max_length=20,
                verbose_name="短信服务商",
            ),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="tencent_sdk_app_id",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="腾讯云 SDK AppID"
            ),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="tencent_secret_id",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="腾讯云 SecretId"
            ),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="tencent_secret_key",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="腾讯云 SecretKey"
            ),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="tencent_sign_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="腾讯云短信签名"
            ),
        ),
        migrations.AddField(
            model_name="verifyconfig",
            name="tencent_template_code",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="腾讯云短信模板码"
            ),
        ),
    ]
