# Generated by Django 6.0.3 on 2026-04-07 03:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity',
                 models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('customization', models.TextField(blank=True, verbose_name='定制要求')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '购物车商品',
                'verbose_name_plural': '购物车商品',
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='订单号')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('confirmed', '已确认'),
                                                     ('preparing', '制作中'), ('ready', '已就绪'),
                                                     ('completed', '已完成'), ('cancelled', '已取消'),
                                                     ('refunded', '已退款')], default='pending', max_length=20)),
                ('order_type',
                 models.CharField(choices=[('dine_in', '堂食'), ('takeaway', '自取'), ('delivery', '外卖')],
                                  default='dine_in', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总额')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='配送费')),
                ('discount_amount',
                 models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='优惠金额')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='支付方式')),
                ('payment_status', models.BooleanField(default=False, verbose_name='支付状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='客户电话')),
                ('customer_notes', models.TextField(blank=True, verbose_name='客户备注')),
                ('delivery_address', models.TextField(blank=True, verbose_name='配送地址')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='期望配送时间')),
                ('pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='取餐时间')),
                ('table_number', models.CharField(blank=True, max_length=20, verbose_name='桌号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('product_image', models.CharField(blank=True, max_length=500, verbose_name='商品图片')),
                ('specifications', models.JSONField(default=dict, verbose_name='规格信息')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('attribute_selections', models.JSONField(default=dict, verbose_name='属性选择')),
                ('customization', models.TextField(blank=True, verbose_name='定制要求')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(
                    choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('cash', '现金'), ('card', '银行卡'),
                             ('balance', '余额支付')], max_length=20)),
                ('payment_status', models.CharField(
                    choices=[('pending', '待支付'), ('paid', '支付成功'), ('failed', '支付失败'),
                             ('refunded', '已退款')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='交易ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('payment_data', models.JSONField(default=dict, verbose_name='支付数据')),
                ('refund_data', models.JSONField(default=dict, verbose_name='退款数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
            ],
            options={
                'verbose_name': '订单支付',
                'verbose_name_plural': '订单支付',
                'db_table': 'order_payments',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(
                    choices=[('pending', '待支付'), ('paid', '已支付'), ('confirmed', '已确认'),
                             ('preparing', '制作中'), ('ready', '已就绪'), ('completed', '已完成'),
                             ('cancelled', '已取消'), ('refunded', '已退款')], max_length=20)),
                ('new_status', models.CharField(
                    choices=[('pending', '待支付'), ('paid', '已支付'), ('confirmed', '已确认'),
                             ('preparing', '制作中'), ('ready', '已就绪'), ('completed', '已完成'),
                             ('cancelled', '已取消'), ('refunded', '已退款')], max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '订单状态日志',
                'verbose_name_plural': '订单状态日志',
                'db_table': 'order_status_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'carts',
            },
        ),
    ]
