# Generated by Django 6.0.6 on 2026-07-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="打印机名称")),
                (
                    "printer_type",
                    models.CharField(
                        choices=[
                            ("usb", "USB打印机"),
                            ("network", "网络打印机"),
                            ("cloud", "云打印机"),
                            ("bluetooth", "蓝牙打印机"),
                        ],
                        default="cloud",
                        max_length=20,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("feie", "飞鹅云打印"),
                            ("yilianyun", "易联云"),
                            ("xinjie", "芯烨"),
                            ("custom", "自定义"),
                        ],
                        default="feie",
                        max_length=20,
                    ),
                ),
                (
                    "device_no",
                    models.CharField(max_length=100, verbose_name="设备编号"),
                ),
                (
                    "device_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="设备密钥"
                    ),
                ),
                (
                    "connection_string",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="连接字符串"
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(blank=True, max_length=50, verbose_name="IP地址"),
                ),
                ("port", models.IntegerField(default=9100, verbose_name="端口")),
                (
                    "paper_width",
                    models.IntegerField(default=80, verbose_name="纸张宽度(mm)"),
                ),
                ("copies", models.IntegerField(default=1, verbose_name="打印份数")),
                (
                    "auto_print",
                    models.BooleanField(default=True, verbose_name="自动打印"),
                ),
                (
                    "print_header",
                    models.BooleanField(default=True, verbose_name="打印抬头"),
                ),
                (
                    "print_footer",
                    models.BooleanField(default=True, verbose_name="打印页脚"),
                ),
                (
                    "print_qrcode",
                    models.BooleanField(default=True, verbose_name="打印二维码"),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="在线状态"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "feie_user",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="飞鹅云用户名"
                    ),
                ),
                (
                    "feie_ukey",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="飞鹅云UKEY"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "打印机",
                "verbose_name_plural": "打印机",
                "db_table": "printers",
            },
        ),
        migrations.CreateModel(
            name="PrintLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(max_length=50, verbose_name="内容类型"),
                ),
                (
                    "reference_id",
                    models.CharField(max_length=100, verbose_name="关联ID"),
                ),
                ("print_content", models.TextField(verbose_name="打印内容")),
                (
                    "is_success",
                    models.BooleanField(default=False, verbose_name="是否成功"),
                ),
                ("copies", models.IntegerField(default=1, verbose_name="打印份数")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "打印日志",
                "verbose_name_plural": "打印日志",
                "db_table": "print_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrintTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="任务ID"
                    ),
                ),
                (
                    "content_data",
                    models.JSONField(default=dict, verbose_name="打印数据"),
                ),
                ("print_content", models.TextField(verbose_name="打印内容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待打印"),
                            ("printing", "打印中"),
                            ("completed", "打印完成"),
                            ("failed", "打印失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("copies", models.IntegerField(default=1, verbose_name="打印份数")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "printed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="打印时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "打印任务",
                "verbose_name_plural": "打印任务",
                "db_table": "print_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrintTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("order", "订单小票"),
                            ("kitchen", "厨房单"),
                            ("receipt", "收据"),
                            ("label", "标签"),
                        ],
                        default="order",
                        max_length=20,
                    ),
                ),
                (
                    "header_template",
                    models.TextField(blank=True, verbose_name="抬头模板"),
                ),
                ("content_template", models.TextField(verbose_name="内容模板")),
                (
                    "footer_template",
                    models.TextField(blank=True, verbose_name="页脚模板"),
                ),
                ("font_size", models.IntegerField(default=14, verbose_name="字体大小")),
                ("line_spacing", models.IntegerField(default=1, verbose_name="行间距")),
                ("margin_top", models.IntegerField(default=5, verbose_name="上边距")),
                (
                    "margin_bottom",
                    models.IntegerField(default=5, verbose_name="下边距"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="默认模板"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "打印模板",
                "verbose_name_plural": "打印模板",
                "db_table": "print_templates",
            },
        ),
    ]
