# Generated by Django 6.0.6 on 2026-07-21 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("printing", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printers",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="printlog",
            name="printer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="print_logs",
                to="printing.printer",
            ),
        ),
        migrations.AddField(
            model_name="printtask",
            name="printer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="print_tasks",
                to="printing.printer",
            ),
        ),
        migrations.AddField(
            model_name="printlog",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="print_logs",
                to="printing.printtask",
            ),
        ),
        migrations.AddField(
            model_name="printtemplate",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="print_templates",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="printtask",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="print_tasks",
                to="printing.printtemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="printtemplate",
            unique_together={("shop", "template_type", "is_default")},
        ),
    ]
