# Generated by Django 6.0.3 on 2026-04-07 08:18

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0001_initial'),
        ('shops', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='优惠券名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='优惠券代码')),
                ('coupon_type',
                 models.CharField(choices=[('fixed', '固定金额'), ('percentage', '百分比'), ('shipping', '免运费')],
                                  default='fixed', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10,
                                              validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                                              verbose_name='优惠值')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True,
                                                     verbose_name='最大折扣金额')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[
                    django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='最低订单金额')),
                ('apply_to',
                 models.CharField(choices=[('all', '全部商品'), ('category', '指定分类'), ('product', '指定商品')],
                                  default='all', max_length=20)),
                ('apply_to_ids', models.JSONField(blank=True, default=list, verbose_name='适用范围ID列表')),
                ('total_quantity', models.IntegerField(verbose_name='发行总量')),
                ('used_quantity', models.IntegerField(default=0, verbose_name='已使用数量')),
                ('valid_from', models.DateTimeField(verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(verbose_name='过期时间')),
                ('limit_per_user', models.IntegerField(default=1, verbose_name='每人限领数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons',
                                           to='shops.shop')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'db_table': 'promotions_coupon',
            },
        ),
        migrations.CreateModel(
            name='CouponRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('rule_type', models.CharField(
                    choices=[('auto_register', '注册自动发放'), ('first_order', '首单完成后发放'),
                             ('birthday', '生日发放'), ('manual', '手动发放')], max_length=20,
                    verbose_name='规则类型')),
                ('config', models.JSONField(default=dict, verbose_name='规则配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules',
                                             to='promotions.coupon')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_rules',
                                           to='shops.shop')),
            ],
            options={
                'verbose_name': '优惠券发放规则',
                'verbose_name_plural': '优惠券发放规则',
                'db_table': 'coupon_rules',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='促销名称')),
                ('promotion_type', models.CharField(
                    choices=[('discount', '折扣'), ('gift', '赠品'), ('combo', '套餐'), ('flash_sale', '限时抢购')],
                    max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='活动描述')),
                ('condition_amount',
                 models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='条件金额')),
                ('condition_quantity', models.IntegerField(blank=True, null=True, verbose_name='条件数量')),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True,
                                                      validators=[
                                                          django.core.validators.MinValueValidator(Decimal('0.00')),
                                                          django.core.validators.MaxValueValidator(Decimal('1.00'))],
                                                      verbose_name='折扣率')),
                ('discount_amount',
                 models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='折扣金额')),
                ('gift_quantity', models.IntegerField(default=1, verbose_name='赠品数量')),
                ('valid_from', models.DateTimeField(verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apply_to_categories',
                 models.ManyToManyField(blank=True, related_name='applicable_promotions', to='products.category',
                                        verbose_name='适用分类')),
                ('apply_to_products',
                 models.ManyToManyField(blank=True, related_name='applicable_promotions', to='products.product',
                                        verbose_name='适用商品')),
                ('gift_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   related_name='gift_promotions', to='products.product',
                                                   verbose_name='赠品')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions',
                                           to='shops.shop')),
            ],
            options={
                'verbose_name': '促销活动',
                'verbose_name_plural': '促销活动',
                'db_table': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', '可用'), ('used', '已使用'), ('expired', '已过期')],
                                            default='available', max_length=20)),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons',
                                             to='promotions.coupon')),
                ('used_in_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                    to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'db_table': 'user_coupons',
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
