# Generated by Django 6.0.6 on 2026-07-22 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0002_initial"),
        ("promotions", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coupons",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="couponrule",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="promotions.coupon",
            ),
        ),
        migrations.AddField(
            model_name="couponrule",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coupon_rules",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="apply_to_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="applicable_promotions",
                to="products.category",
                verbose_name="适用分类",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="apply_to_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="applicable_promotions",
                to="products.product",
                verbose_name="适用商品",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="gift_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gift_promotions",
                to="products.product",
                verbose_name="赠品",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="promotions",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="usercoupon",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_coupons",
                to="promotions.coupon",
            ),
        ),
        migrations.AddField(
            model_name="usercoupon",
            name="used_in_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.order",
            ),
        ),
    ]
