# Generated by Django 6.0.6 on 2026-07-22 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pos", "0001_initial"),
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cashiershift",
            name="cashier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="收银员",
            ),
        ),
        migrations.AddField(
            model_name="cashiershift",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cashier_shifts",
                to="shops.shop",
            ),
        ),
    ]
