# Generated by Django 6.0.6 on 2026-07-22 01:56

from decimal import Decimal

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlipayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.CharField(max_length=32, verbose_name="AppID")),
                (
                    "app_private_key",
                    encrypted_model_fields.fields.EncryptedTextField(
                        verbose_name="应用私钥"
                    ),
                ),
                (
                    "alipay_public_key",
                    encrypted_model_fields.fields.EncryptedTextField(
                        verbose_name="支付宝公钥"
                    ),
                ),
                (
                    "enable_app",
                    models.BooleanField(default=True, verbose_name="启用APP支付"),
                ),
                (
                    "enable_wap",
                    models.BooleanField(default=True, verbose_name="启用手机网站支付"),
                ),
                (
                    "enable_pc",
                    models.BooleanField(default=True, verbose_name="启用电脑网站支付"),
                ),
                (
                    "notify_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="支付回调地址"
                    ),
                ),
                (
                    "return_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="返回地址"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "支付宝配置",
                "verbose_name_plural": "支付宝配置",
                "db_table": "alipay_configs",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="支付方式名称")),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("wechat", "微信支付"),
                            ("alipay", "支付宝"),
                            ("cash", "现金"),
                            ("card", "银行卡"),
                            ("balance", "余额支付"),
                            ("points", "积分支付"),
                        ],
                        max_length=20,
                        verbose_name="支付代码",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("config", models.JSONField(default=dict, verbose_name="支付配置")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "支付方式",
                "verbose_name_plural": "支付方式",
                "db_table": "payment_methods",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_no",
                    models.CharField(max_length=64, unique=True, verbose_name="交易号"),
                ),
                (
                    "out_trade_no",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="商户订单号"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="支付金额",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "支付成功"),
                            ("failed", "支付失败"),
                            ("refunded", "已退款"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "thirdparty_trade_no",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="第三方交易号"
                    ),
                ),
                (
                    "payment_data",
                    models.JSONField(default=dict, verbose_name="支付数据"),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="退款金额",
                    ),
                ),
                (
                    "refund_data",
                    models.JSONField(default=dict, verbose_name="退款数据"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退款时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "支付交易",
                "verbose_name_plural": "支付交易",
                "db_table": "payment_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_no",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="退款单号"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="退款金额",
                    ),
                ),
                ("reason", models.TextField(verbose_name="退款原因")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("approved", "已同意"),
                            ("rejected", "已拒绝"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reject_reason",
                    models.TextField(blank=True, verbose_name="拒绝原因"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "退款申请",
                "verbose_name_plural": "退款申请",
                "db_table": "refund_requests",
            },
        ),
        migrations.CreateModel(
            name="WechatPayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.CharField(max_length=64, verbose_name="AppID")),
                ("mch_id", models.CharField(max_length=32, verbose_name="商户号")),
                (
                    "api_key",
                    encrypted_model_fields.fields.EncryptedCharField(
                        verbose_name="API密钥"
                    ),
                ),
                (
                    "cert_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="证书路径"
                    ),
                ),
                (
                    "key_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="密钥路径"
                    ),
                ),
                (
                    "enable_jsapi",
                    models.BooleanField(default=True, verbose_name="启用JSAPI支付"),
                ),
                (
                    "enable_miniprogram",
                    models.BooleanField(default=True, verbose_name="启用小程序支付"),
                ),
                (
                    "enable_native",
                    models.BooleanField(default=True, verbose_name="启用扫码支付"),
                ),
                (
                    "notify_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="支付回调地址"
                    ),
                ),
                (
                    "refund_notify_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="退款回调地址"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "微信支付配置",
                "verbose_name_plural": "微信支付配置",
                "db_table": "wechat_pay_configs",
            },
        ),
    ]
