# Generated by Django 6.0.6 on 2026-07-22 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("payments", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alipayconfig",
            name="shop",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alipay_config",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shop_payment_methods",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_transactions",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="payments.paymentmethod"
            ),
        ),
    ]
