# Generated by Django 6.0.6 on 2026-07-22 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0002_initial"),
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="refundrequest",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refunds",
                to="payments.paymenttransaction",
            ),
        ),
        migrations.AddField(
            model_name="wechatpayconfig",
            name="shop",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wechat_pay_config",
                to="shops.shop",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethod",
            unique_together={("shop", "code")},
        ),
    ]
