# Generated by Django 6.0.3 on 2026-04-07 03:42

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('shops', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='分类图片')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='children', to='products.category', verbose_name='父级分类')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories',
                                           to='shops.shop')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'product_categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('shop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[
                    django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='基础价格')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[
                    django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='成本价')),
                ('main_image', models.ImageField(upload_to='products/main/', verbose_name='主图')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='商品图集')),
                ('status', models.CharField(
                    choices=[('draft', '草稿'), ('active', '上架'), ('inactive', '下架'), ('out_of_stock', '缺货')],
                    default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, verbose_name='推荐商品')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('allow_customization', models.BooleanField(default=False, verbose_name='允许定制')),
                ('preparation_time', models.IntegerField(default=10, verbose_name='准备时间(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products',
                                   to='products.category', verbose_name='商品分类')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products',
                                           to='shops.shop')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='属性名称')),
                ('attribute_type', models.CharField(
                    choices=[('text', '文本'), ('number', '数字'), ('select', '选择'), ('checkbox', '复选框')],
                    default='select', max_length=20)),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必选')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes',
                                              to='products.product')),
            ],
            options={
                'verbose_name': '商品属性',
                'verbose_name_plural': '商品属性',
                'db_table': 'product_attributes',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='选项值')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[
                    django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='附加价格')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options',
                                                to='products.productattribute')),
            ],
            options={
                'verbose_name': '商品属性选项',
                'verbose_name_plural': '商品属性选项',
                'db_table': 'product_attribute_options',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='替代文本')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images',
                                   to='products.product')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 'product_images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=100, unique=True, verbose_name='SKU编码')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10,
                                              validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                                              verbose_name='销售价格')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[
                    django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='成本价')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('low_stock_threshold', models.IntegerField(default=5, verbose_name='低库存阈值')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/skus/', verbose_name='SKU图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus',
                                              to='products.product')),
            ],
            options={
                'verbose_name': '商品SKU',
                'verbose_name_plural': '商品SKU',
                'db_table': 'product_skus',
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(
                    choices=[('purchase', '采购入库'), ('sale', '销售出库'), ('adjustment', '库存调整'),
                             ('return', '退货入库'), ('waste', '报损出库')], max_length=20)),
                ('quantity_change', models.IntegerField(verbose_name='数量变化')),
                ('current_quantity', models.IntegerField(verbose_name='变更后数量')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='关联单据ID')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs',
                                          to='products.productsku')),
            ],
            options={
                'verbose_name': '库存日志',
                'verbose_name_plural': '库存日志',
                'db_table': 'inventory_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='规格名称')),
                ('display_name', models.CharField(max_length=50, verbose_name='显示名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications',
                                           to='shops.shop')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
                'db_table': 'specifications',
                'unique_together': {('shop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='规格值')),
                ('display_value', models.CharField(max_length=50, verbose_name='显示值')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values',
                                                    to='products.specification')),
            ],
            options={
                'verbose_name': '规格值',
                'verbose_name_plural': '规格值',
                'db_table': 'specification_values',
                'unique_together': {('specification', 'value')},
            },
        ),
        migrations.AddField(
            model_name='productsku',
            name='specifications',
            field=models.ManyToManyField(blank=True, to='products.specificationvalue', verbose_name='规格组合'),
        ),
    ]
