# Generated by Django 6.0.6 on 2026-07-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="条形码",
            ),
        ),
        migrations.AddField(
            model_name="productsku",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="条形码",
            ),
        ),
    ]
