# Generated by Django 6.0.6 on 2026-07-22 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0002_initial"),
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorylog",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.category",
                verbose_name="商品分类",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productattributeoption",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="products.productattribute",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productsku",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skus",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="inventorylog",
            name="sku",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_logs",
                to="products.productsku",
            ),
        ),
        migrations.AddField(
            model_name="specification",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specifications",
                to="shops.shop",
            ),
        ),
        migrations.AddField(
            model_name="specificationvalue",
            name="specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="products.specification",
            ),
        ),
        migrations.AddField(
            model_name="productsku",
            name="specifications",
            field=models.ManyToManyField(
                blank=True, to="products.specificationvalue", verbose_name="规格组合"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("shop", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="specification",
            unique_together={("shop", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="specificationvalue",
            unique_together={("specification", "value")},
        ),
    ]
