# Generated by Django 6.0.6 on 2026-07-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/main/", verbose_name="主图"
            ),
        ),
    ]
