# Generated by Django 6.0.6 on 2026-07-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/gallery/",
                verbose_name="图片",
            ),
        ),
    ]
